# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/axi_pcie_0.xci
# IP: The module: 'axi_pcie_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/axi_pcie_0/source/axi_pcie_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pcie_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/synth/axi_pcie_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pcie_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/axi_pcie_0.xci
# IP: The module: 'axi_pcie_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/axi_pcie_0/source/axi_pcie_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pcie_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/user/ocpi/bsp_sidekiq_m2_cp_dev1_5_cv2_8/hdl/platforms/m2pcie/axi_pcie_wrapper/core/axi_pcie_0/synth/axi_pcie_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pcie_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
